### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by lnnrtwttkhn** [lnnrtwttkhn/bibliography#41]
build failed: https://app.travis-ci.com/github/lnnrtwttkhn/bibliography/builds/240569123

```bash
 make

python3 code/parser.py

Traceback (most recent call last):

  File "code/parser.py", line 4, in <module>

    import bibtexparser

  File "/home/travis/.local/lib/python3.5/site-packages/bibtexparser/__init__.py", line 30, in <module>

    from . import bibdatabase, bibtexexpression, bparser, bwriter, latexenc, customization

  File "/home/travis/.local/lib/python3.5/site-packages/bibtexparser/bibtexexpression.py", line 1, in <module>

    import pyparsing as pp

  File "/home/travis/.local/lib/python3.5/site-packages/pyparsing/__init__.py", line 112, in <module>

    from .util import *

  File "/home/travis/.local/lib/python3.5/site-packages/pyparsing/util.py", line 16

    _all_names: List[str] = []

              ^

SyntaxError: invalid syntax

Makefile:5: recipe for target 'bibliography.csv' failed
```

**Comment by lnnrtwttkhn** [comment]
I think this is fixed
